"""add student information and staff management tables

Revision ID: 22493032eab9
Revises: fd5a7543182b
Create Date: 2026-08-25 21:16:23.959268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22493032eab9'
down_revision: Union[str, Sequence[str], None] = 'fd5a7543182b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardians',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_email'), 'guardians', ['email'], unique=False)
    op.create_index(op.f('ix_guardians_phone'), 'guardians', ['phone'], unique=False)
    op.create_table('staff',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('employee_no', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_employee_no'), 'staff', ['employee_no'], unique=True)
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=True)
    op.create_table('staff_assignments',
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_assignments_academic_year_id'), 'staff_assignments', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_staff_assignments_section_id'), 'staff_assignments', ['section_id'], unique=False)
    op.create_index('ix_staff_assignments_section_term', 'staff_assignments', ['section_id', 'term_id'], unique=False)
    op.create_index(op.f('ix_staff_assignments_staff_id'), 'staff_assignments', ['staff_id'], unique=False)
    op.create_index('ix_staff_assignments_staff_term', 'staff_assignments', ['staff_id', 'term_id'], unique=False)
    op.create_index(op.f('ix_staff_assignments_term_id'), 'staff_assignments', ['term_id'], unique=False)
    op.create_table('staff_attendance',
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('marked_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_attendance_staff_date', 'staff_attendance', ['staff_id', 'date'], unique=True)
    op.create_index(op.f('ix_staff_attendance_staff_id'), 'staff_attendance', ['staff_id'], unique=False)
    op.create_table('staff_documents',
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_documents_staff_id'), 'staff_documents', ['staff_id'], unique=False)
    op.create_table('students',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('admission_no', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('current_section_id', sa.String(length=36), nullable=True),
    sa.Column('enrollment_status', sa.String(length=20), nullable=False),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['current_section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_admission_no'), 'students', ['admission_no'], unique=True)
    op.create_index(op.f('ix_students_current_section_id'), 'students', ['current_section_id'], unique=False)
    op.create_index(op.f('ix_students_enrollment_status'), 'students', ['enrollment_status'], unique=False)
    op.create_table('student_academic_history',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('promotion_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_academic_history_academic_year_id'), 'student_academic_history', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_student_academic_history_student_id'), 'student_academic_history', ['student_id'], unique=False)
    op.create_table('student_documents',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_documents_student_id'), 'student_documents', ['student_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('guardian_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_billing_contact', sa.Boolean(), nullable=False),
    sa.Column('can_pickup', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_guardians_guardian_id'), 'student_guardians', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_guardian_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_student_documents_student_id'), table_name='student_documents')
    op.drop_table('student_documents')
    op.drop_index(op.f('ix_student_academic_history_student_id'), table_name='student_academic_history')
    op.drop_index(op.f('ix_student_academic_history_academic_year_id'), table_name='student_academic_history')
    op.drop_table('student_academic_history')
    op.drop_index(op.f('ix_students_enrollment_status'), table_name='students')
    op.drop_index(op.f('ix_students_current_section_id'), table_name='students')
    op.drop_index(op.f('ix_students_admission_no'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staff_documents_staff_id'), table_name='staff_documents')
    op.drop_table('staff_documents')
    op.drop_index(op.f('ix_staff_attendance_staff_id'), table_name='staff_attendance')
    op.drop_index('ix_staff_attendance_staff_date', table_name='staff_attendance')
    op.drop_table('staff_attendance')
    op.drop_index(op.f('ix_staff_assignments_term_id'), table_name='staff_assignments')
    op.drop_index('ix_staff_assignments_staff_term', table_name='staff_assignments')
    op.drop_index(op.f('ix_staff_assignments_staff_id'), table_name='staff_assignments')
    op.drop_index('ix_staff_assignments_section_term', table_name='staff_assignments')
    op.drop_index(op.f('ix_staff_assignments_section_id'), table_name='staff_assignments')
    op.drop_index(op.f('ix_staff_assignments_academic_year_id'), table_name='staff_assignments')
    op.drop_table('staff_assignments')
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_employee_no'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_guardians_phone'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_email'), table_name='guardians')
    op.drop_table('guardians')
    # ### end Alembic commands ###
