"""add fees, attendance, academic performance, examinations

Revision ID: fa98eaaed377
Revises: 22493032eab9
Create Date: 2026-08-26 07:04:08.545223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa98eaaed377'
down_revision: Union[str, Sequence[str], None] = '22493032eab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_weight_pct', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fee_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grading_scales',
    sa.Column('grading_scale_set_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('letter_grade', sa.String(length=50), nullable=False),
    sa.Column('gpa_points', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_scales_grading_scale_set_id'), 'grading_scales', ['grading_scale_set_id'], unique=False)
    op.create_index('ix_grading_scales_set_range', 'grading_scales', ['grading_scale_set_id', 'min_score', 'max_score'], unique=False)
    op.create_table('assessments',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_type_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_by_staff_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_types.id'], ),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_assessment_type_id'), 'assessments', ['assessment_type_id'], unique=False)
    op.create_index(op.f('ix_assessments_section_id'), 'assessments', ['section_id'], unique=False)
    op.create_index('ix_assessments_section_subject_term', 'assessments', ['section_id', 'subject_id', 'term_id'], unique=False)
    op.create_index(op.f('ix_assessments_subject_id'), 'assessments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_assessments_term_id'), 'assessments', ['term_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('taken_by_staff_id', sa.String(length=36), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['taken_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_sessions_section_date', 'attendance_sessions', ['section_id', 'date'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_section_id'), 'attendance_sessions', ['section_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_subject_id'), 'attendance_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_taken_by_staff_id'), 'attendance_sessions', ['taken_by_staff_id'], unique=False)
    op.create_table('exams',
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exam_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_term_id'), 'exams', ['term_id'], unique=False)
    op.create_table('fee_structures',
    sa.Column('academic_year_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('fee_category_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structures_academic_year_id'), 'fee_structures', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_class_id'), 'fee_structures', ['class_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_fee_category_id'), 'fee_structures', ['fee_category_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_term_id'), 'fee_structures', ['term_id'], unique=False)
    op.create_table('absenteeism_flags',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('consecutive_absences', sa.Integer(), nullable=False),
    sa.Column('attendance_rate', sa.Float(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absenteeism_flags_student_id'), 'absenteeism_flags', ['student_id'], unique=False)
    op.create_index('ix_absenteeism_flags_student_term', 'absenteeism_flags', ['student_id', 'term_id'], unique=False)
    op.create_index(op.f('ix_absenteeism_flags_term_id'), 'absenteeism_flags', ['term_id'], unique=False)
    op.create_table('attendance_daily_summary',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_daily_summary_student_date', 'attendance_daily_summary', ['student_id', 'date'], unique=True)
    op.create_index(op.f('ix_attendance_daily_summary_student_id'), 'attendance_daily_summary', ['student_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index('ix_attendance_records_session_student', 'attendance_records', ['session_id', 'student_id'], unique=True)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('discounts',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('applies_to', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_threshold_cents', sa.Integer(), nullable=True),
    sa.Column('fee_category_id', sa.String(length=36), nullable=True),
    sa.Column('fee_structure_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fee_category_id'], ['fee_categories.id'], ),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_schedules',
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_schedules_exam_id'), 'exam_schedules', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_section_id'), 'exam_schedules', ['section_id'], unique=False)
    op.create_index('ix_exam_schedules_section_subject', 'exam_schedules', ['section_id', 'subject_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_subject_id'), 'exam_schedules', ['subject_id'], unique=False)
    op.create_table('fee_invoices',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('fee_structure_id', sa.String(length=36), nullable=False),
    sa.Column('amount_due_cents', sa.Integer(), nullable=False),
    sa.Column('credit_applied_cents', sa.Integer(), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_invoices_fee_structure_id'), 'fee_invoices', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_fee_invoices_status'), 'fee_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_fee_invoices_student_id'), 'fee_invoices', ['student_id'], unique=False)
    op.create_index(op.f('ix_fee_invoices_term_id'), 'fee_invoices', ['term_id'], unique=False)
    op.create_table('fee_ledger',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('balance_after_cents', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('term_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_ledger_entry_type'), 'fee_ledger', ['entry_type'], unique=False)
    op.create_index(op.f('ix_fee_ledger_student_id'), 'fee_ledger', ['student_id'], unique=False)
    op.create_index(op.f('ix_fee_ledger_term_id'), 'fee_ledger', ['term_id'], unique=False)
    op.create_table('fee_payments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('received_by_staff_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('voided_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['received_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payments_idempotency_key'), 'fee_payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_fee_payments_student_id'), 'fee_payments', ['student_id'], unique=False)
    op.create_table('report_cards',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('compiled_by_staff_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_grade', sa.String(length=50), nullable=True),
    sa.Column('class_rank', sa.Integer(), nullable=True),
    sa.Column('attendance_summary_snapshot', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['compiled_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_cards_student_id'), 'report_cards', ['student_id'], unique=False)
    op.create_index('ix_report_cards_student_term', 'report_cards', ['student_id', 'term_id'], unique=True)
    op.create_index(op.f('ix_report_cards_term_id'), 'report_cards', ['term_id'], unique=False)
    op.create_table('student_fee_overrides',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('fee_structure_id', sa.String(length=36), nullable=False),
    sa.Column('override_amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fee_overrides_fee_structure_id'), 'student_fee_overrides', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_student_fee_overrides_student_id'), 'student_fee_overrides', ['student_id'], unique=False)
    op.create_table('student_scores',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('score_obtained', sa.Float(), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('graded_by_staff_id', sa.String(length=36), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['graded_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_scores_assessment_id'), 'student_scores', ['assessment_id'], unique=False)
    op.create_index('ix_student_scores_assessment_student', 'student_scores', ['assessment_id', 'student_id'], unique=True)
    op.create_index(op.f('ix_student_scores_student_id'), 'student_scores', ['student_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('exam_schedule_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('score_obtained', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exam_schedule_id'], ['exam_schedules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_results_exam_schedule_id'), 'exam_results', ['exam_schedule_id'], unique=False)
    op.create_index('ix_exam_results_schedule_student', 'exam_results', ['exam_schedule_id', 'student_id'], unique=True)
    op.create_index(op.f('ix_exam_results_student_id'), 'exam_results', ['student_id'], unique=False)
    op.create_table('excuse_requests',
    sa.Column('attendance_record_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_staff_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excuse_requests_attendance_record_id'), 'excuse_requests', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_excuse_requests_requested_by_user_id'), 'excuse_requests', ['requested_by_user_id'], unique=False)
    op.create_table('fee_credits',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('source_payment_id', sa.String(length=36), nullable=False),
    sa.Column('originating_term_id', sa.String(length=36), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_remaining_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['originating_term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['source_payment_id'], ['fee_payments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_credits_source_payment_id'), 'fee_credits', ['source_payment_id'], unique=False)
    op.create_index(op.f('ix_fee_credits_status'), 'fee_credits', ['status'], unique=False)
    op.create_index(op.f('ix_fee_credits_student_id'), 'fee_credits', ['student_id'], unique=False)
    op.create_table('fee_payment_allocations',
    sa.Column('fee_payment_id', sa.String(length=36), nullable=False),
    sa.Column('fee_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fee_invoice_id'], ['fee_invoices.id'], ),
    sa.ForeignKeyConstraint(['fee_payment_id'], ['fee_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_payment_allocations_fee_invoice_id'), 'fee_payment_allocations', ['fee_invoice_id'], unique=False)
    op.create_index(op.f('ix_fee_payment_allocations_fee_payment_id'), 'fee_payment_allocations', ['fee_payment_id'], unique=False)
    op.create_table('receipts',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['fee_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_payment_id'), 'receipts', ['payment_id'], unique=True)
    op.create_index(op.f('ix_receipts_receipt_no'), 'receipts', ['receipt_no'], unique=True)
    op.create_table('report_card_comments',
    sa.Column('report_card_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('author_staff_id', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['report_card_id'], ['report_cards.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_card_comments_report_card_id'), 'report_card_comments', ['report_card_id'], unique=False)
    op.create_table('student_discounts',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('discount_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_discounts_discount_id'), 'student_discounts', ['discount_id'], unique=False)
    op.create_index(op.f('ix_student_discounts_student_id'), 'student_discounts', ['student_id'], unique=False)
    op.create_table('fee_credit_applications',
    sa.Column('fee_credit_id', sa.String(length=36), nullable=False),
    sa.Column('fee_invoice_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('applied_by_staff_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['fee_credit_id'], ['fee_credits.id'], ),
    sa.ForeignKeyConstraint(['fee_invoice_id'], ['fee_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_credit_applications_fee_credit_id'), 'fee_credit_applications', ['fee_credit_id'], unique=False)
    op.create_index(op.f('ix_fee_credit_applications_fee_invoice_id'), 'fee_credit_applications', ['fee_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_credit_applications_fee_invoice_id'), table_name='fee_credit_applications')
    op.drop_index(op.f('ix_fee_credit_applications_fee_credit_id'), table_name='fee_credit_applications')
    op.drop_table('fee_credit_applications')
    op.drop_index(op.f('ix_student_discounts_student_id'), table_name='student_discounts')
    op.drop_index(op.f('ix_student_discounts_discount_id'), table_name='student_discounts')
    op.drop_table('student_discounts')
    op.drop_index(op.f('ix_report_card_comments_report_card_id'), table_name='report_card_comments')
    op.drop_table('report_card_comments')
    op.drop_index(op.f('ix_receipts_receipt_no'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_payment_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_fee_payment_allocations_fee_payment_id'), table_name='fee_payment_allocations')
    op.drop_index(op.f('ix_fee_payment_allocations_fee_invoice_id'), table_name='fee_payment_allocations')
    op.drop_table('fee_payment_allocations')
    op.drop_index(op.f('ix_fee_credits_student_id'), table_name='fee_credits')
    op.drop_index(op.f('ix_fee_credits_status'), table_name='fee_credits')
    op.drop_index(op.f('ix_fee_credits_source_payment_id'), table_name='fee_credits')
    op.drop_table('fee_credits')
    op.drop_index(op.f('ix_excuse_requests_requested_by_user_id'), table_name='excuse_requests')
    op.drop_index(op.f('ix_excuse_requests_attendance_record_id'), table_name='excuse_requests')
    op.drop_table('excuse_requests')
    op.drop_index(op.f('ix_exam_results_student_id'), table_name='exam_results')
    op.drop_index('ix_exam_results_schedule_student', table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_exam_schedule_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_student_scores_student_id'), table_name='student_scores')
    op.drop_index('ix_student_scores_assessment_student', table_name='student_scores')
    op.drop_index(op.f('ix_student_scores_assessment_id'), table_name='student_scores')
    op.drop_table('student_scores')
    op.drop_index(op.f('ix_student_fee_overrides_student_id'), table_name='student_fee_overrides')
    op.drop_index(op.f('ix_student_fee_overrides_fee_structure_id'), table_name='student_fee_overrides')
    op.drop_table('student_fee_overrides')
    op.drop_index(op.f('ix_report_cards_term_id'), table_name='report_cards')
    op.drop_index('ix_report_cards_student_term', table_name='report_cards')
    op.drop_index(op.f('ix_report_cards_student_id'), table_name='report_cards')
    op.drop_table('report_cards')
    op.drop_index(op.f('ix_fee_payments_student_id'), table_name='fee_payments')
    op.drop_index(op.f('ix_fee_payments_idempotency_key'), table_name='fee_payments')
    op.drop_table('fee_payments')
    op.drop_index(op.f('ix_fee_ledger_term_id'), table_name='fee_ledger')
    op.drop_index(op.f('ix_fee_ledger_student_id'), table_name='fee_ledger')
    op.drop_index(op.f('ix_fee_ledger_entry_type'), table_name='fee_ledger')
    op.drop_table('fee_ledger')
    op.drop_index(op.f('ix_fee_invoices_term_id'), table_name='fee_invoices')
    op.drop_index(op.f('ix_fee_invoices_student_id'), table_name='fee_invoices')
    op.drop_index(op.f('ix_fee_invoices_status'), table_name='fee_invoices')
    op.drop_index(op.f('ix_fee_invoices_fee_structure_id'), table_name='fee_invoices')
    op.drop_table('fee_invoices')
    op.drop_index(op.f('ix_exam_schedules_subject_id'), table_name='exam_schedules')
    op.drop_index('ix_exam_schedules_section_subject', table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_section_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_exam_id'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_table('discounts')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index('ix_attendance_records_session_student', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_attendance_daily_summary_student_id'), table_name='attendance_daily_summary')
    op.drop_index('ix_attendance_daily_summary_student_date', table_name='attendance_daily_summary')
    op.drop_table('attendance_daily_summary')
    op.drop_index(op.f('ix_absenteeism_flags_term_id'), table_name='absenteeism_flags')
    op.drop_index('ix_absenteeism_flags_student_term', table_name='absenteeism_flags')
    op.drop_index(op.f('ix_absenteeism_flags_student_id'), table_name='absenteeism_flags')
    op.drop_table('absenteeism_flags')
    op.drop_index(op.f('ix_fee_structures_term_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_fee_category_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_class_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_academic_year_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_exams_term_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_attendance_sessions_taken_by_staff_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_subject_id'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_section_id'), table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_section_date', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_assessments_term_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_subject_id'), table_name='assessments')
    op.drop_index('ix_assessments_section_subject_term', table_name='assessments')
    op.drop_index(op.f('ix_assessments_section_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_type_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('ix_grading_scales_set_range', table_name='grading_scales')
    op.drop_index(op.f('ix_grading_scales_grading_scale_set_id'), table_name='grading_scales')
    op.drop_table('grading_scales')
    op.drop_table('fee_categories')
    op.drop_table('assessment_types')
    # ### end Alembic commands ###
